version: "3"
services:
  communication:
    build: .
    volumes: 
      - /node_modules
      - ./:/app
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'